on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
      # env:
      #    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          pre-release: beta
          package-name: release-please-action
